spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/blockchain
    username: postgres
    password: 1208
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate